#define SURFACE_DATA_COLOR 0
#define SURFACE_DATA_NORMAL 1
#define SURFACE_DATA_DEPTH 2
#define SURFACE_DATA_WHITE 3
#define SURFACE_DATA_WORLDCOORDS 4
#define SURFACE_DATA_AGGREGATION 5
#define SURFACE_DATA_UV 6

#define SHADING_OFF 0
#define SHADING_DEFERRED_MSAA 1
#define SHADING_DEFERRED_SIMPLE 2

#define WAVING_NONE 0
#define WAVING_WIND_TOP 1
#define WAVING_WIND_WHOLE 2
#define WAVING_LIQUID_SURFACE 3
#define WAVING_LIQUID_TOP 4

#define ALPHA_CHANNEL_UNUSED 0
#define ALPHA_CHANNEL_ALPHA_TEST 1
#define ALPHA_CHANNEL_TRANSPARENCY 2
#define ALPHA_CHANNEL_GLOW 3

#define AGGREGATION_NONE 0
#define AGGREGATION_LINES 1
#define AGGREGATION_SQUARES 2
#define AGGREGATION_SQUARES_EXT 3

#define FACE_LEFT 0
#define FACE_RIGHT 1
#define FACE_FRONT 2
#define FACE_BACK 3
#define FACE_BOTTOM 4
#define FACE_TOP 5

#define FACE_FLAG_LEFT (1 << FACE_LEFT)
#define FACE_FLAG_RIGHT (1 << FACE_RIGHT)
#define FACE_FLAG_FRONT (1 << FACE_FRONT)
#define FACE_FLAG_BACK (1 << FACE_BACK)
#define FACE_FLAG_BOTTOM (1 << FACE_BOTTOM)
#define FACE_FLAG_TOP (1 << FACE_TOP)